### PR TITLE
chore: acrolinx fixes for reference, mlflow and getting_started in 0.10.2

### PR DESCRIPTION
**Pull request by niehaus59**
## Related Issues/PRs

#xxx

## What changes are proposed in this pull request?

 acrolinx fixes for reference, mlflow and getting_started in 0.10.2

## How is this patch tested?

- [ ] I have written tests (not required for typo or doc fix) and confirmed the proposed feature/bug-fix/change works.

## Does this PR change any dependencies?

- [x] No. You can skip this section.
- [ ] Yes. Make sure the dependencies are resolved correctly, and list changes here.

## Does this PR add a new feature? If so, have you added samples on website?

- [x] No. You can skip this section.
- [ ] Yes. Make sure you have added samples following below steps.

1. Find the corresponding markdown file for your new feature in `website/docs/documentation` folder.
   Make sure you choose the correct class `estimators/transformers` and namespace.
2. Follow the pattern in markdown file and add another section for your new API, including pyspark, scala (and .NET potentially) samples.
3. Make sure the `DocTable` points to correct API link.
4. Navigate to website folder, and run `yarn run start` to make sure the website renders correctly.
5. Don't forget to add `<!--pytest-codeblocks:cont-->` before each python code blocks to enable auto-tests for python samples.
6. Make sure the `WebsiteSamplesTests` job pass in the pipeline.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [website/versioned_docs/version-0.10.0/reference/vagrant.md](https://github.com/microsoft/SynapseML/blob/3029697157ba4518aebf0f92d8917714f5a74635/website%2Fversioned_docs%2Fversion-0.10.0%2Freference%2Fvagrant.md) | 92 | 100 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/369e5341-f08e-47c9-943b-5173d684404c) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.1/reference/vagrant.md](https://github.com/microsoft/SynapseML/blob/3029697157ba4518aebf0f92d8917714f5a74635/website%2Fversioned_docs%2Fversion-0.10.1%2Freference%2Fvagrant.md) | 92 | 100 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f09c753-00c9-4ef7-a72d-f67b96408dd5) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/getting_started/dotnet_example.md](https://github.com/microsoft/SynapseML/blob/3029697157ba4518aebf0f92d8917714f5a74635/website%2Fversioned_docs%2Fversion-0.10.2%2Fgetting_started%2Fdotnet_example.md) | 81 | 100 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b9ae248-6ac0-46df-ab96-4c06e613c41a) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/getting_started/first_example.md](https://github.com/microsoft/SynapseML/blob/3029697157ba4518aebf0f92d8917714f5a74635/website%2Fversioned_docs%2Fversion-0.10.2%2Fgetting_started%2Ffirst_example.md) | 94 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9d91351-e070-4ea2-8f24-2c2edc9d248c) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/getting_started/first_model.md](https://github.com/microsoft/SynapseML/blob/3029697157ba4518aebf0f92d8917714f5a74635/website%2Fversioned_docs%2Fversion-0.10.2%2Fgetting_started%2Ffirst_model.md) | 97 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c07c0eb7-d2c3-4cec-a99d-df98d2f03dc1) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/getting_started/installation.md](https://github.com/microsoft/SynapseML/blob/3029697157ba4518aebf0f92d8917714f5a74635/website%2Fversioned_docs%2Fversion-0.10.2%2Fgetting_started%2Finstallation.md) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7496c6e3-26ad-4575-a6bb-1eaf2649f35d) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/mlflow/autologging.md](https://github.com/microsoft/SynapseML/blob/3029697157ba4518aebf0f92d8917714f5a74635/website%2Fversioned_docs%2Fversion-0.10.2%2Fmlflow%2Fautologging.md) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1bcd9fbb-5b45-4af0-b77e-157c866f4e03) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/mlflow/examples.md](https://github.com/microsoft/SynapseML/blob/3029697157ba4518aebf0f92d8917714f5a74635/website%2Fversioned_docs%2Fversion-0.10.2%2Fmlflow%2Fexamples.md) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2178f76c-f41c-49c5-a53c-07fe1b0c49f4) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/mlflow/introduction.md](https://github.com/microsoft/SynapseML/blob/3029697157ba4518aebf0f92d8917714f5a74635/website%2Fversioned_docs%2Fversion-0.10.2%2Fmlflow%2Fintroduction.md) | 94 | 100 | 73 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d213c1fb-bc5c-401c-8bad-32cf67a1011a) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/reference/R-setup.md](https://github.com/microsoft/SynapseML/blob/3029697157ba4518aebf0f92d8917714f5a74635/website%2Fversioned_docs%2Fversion-0.10.2%2Freference%2FR-setup.md) | 93 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d295081a-ae15-4285-a112-ec7b176182a5) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/reference/SAR.md](https://github.com/microsoft/SynapseML/blob/3029697157ba4518aebf0f92d8917714f5a74635/website%2Fversioned_docs%2Fversion-0.10.2%2Freference%2FSAR.md) | 90 | 100 | 75 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b45b1f5-8bed-479c-bb2c-2163ab1d2cd9) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/reference/contributing_guide.md](https://github.com/microsoft/SynapseML/blob/3029697157ba4518aebf0f92d8917714f5a74635/website%2Fversioned_docs%2Fversion-0.10.2%2Freference%2Fcontributing_guide.md) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec74afb8-74a8-4466-a194-fef8c5ec8143) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/reference/cyber.md](https://github.com/microsoft/SynapseML/blob/3029697157ba4518aebf0f92d8917714f5a74635/website%2Fversioned_docs%2Fversion-0.10.2%2Freference%2Fcyber.md) | 95 | 100 | 88 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc313db8-830d-4776-b939-ef04f2668096) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/reference/developer-readme.md](https://github.com/microsoft/SynapseML/blob/3029697157ba4518aebf0f92d8917714f5a74635/website%2Fversioned_docs%2Fversion-0.10.2%2Freference%2Fdeveloper-readme.md) | 93 | 100 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a30a4e1-58bf-4873-b4bb-54ec0d8a7e05) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/reference/docker.md](https://github.com/microsoft/SynapseML/blob/3029697157ba4518aebf0f92d8917714f5a74635/website%2Fversioned_docs%2Fversion-0.10.2%2Freference%2Fdocker.md) | 93 | 100 | 88 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b9ece0e-ea2a-46a0-87d1-d02c74742750) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/reference/dotnet-setup.md](https://github.com/microsoft/SynapseML/blob/3029697157ba4518aebf0f92d8917714f5a74635/website%2Fversioned_docs%2Fversion-0.10.2%2Freference%2Fdotnet-setup.md) | 91 | 100 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e93adbad-1bba-4100-902d-564193a019fe) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/reference/vagrant.md](https://github.com/microsoft/SynapseML/blob/3029697157ba4518aebf0f92d8917714f5a74635/website%2Fversioned_docs%2Fversion-0.10.2%2Freference%2Fvagrant.md) | 92 | 100 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/949f4e1e-10b4-40d0-a457-8c80c5fe6f58) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.9.4/reference/vagrant.md](https://github.com/microsoft/SynapseML/blob/3029697157ba4518aebf0f92d8917714f5a74635/website%2Fversioned_docs%2Fversion-0.9.4%2Freference%2Fvagrant.md) | 92 | 100 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51362225-e934-467c-802e-9892fb6903ae) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.9.5/reference/vagrant.md](https://github.com/microsoft/SynapseML/blob/3029697157ba4518aebf0f92d8917714f5a74635/website%2Fversioned_docs%2Fversion-0.9.5%2Freference%2Fvagrant.md) | 92 | 100 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4e7d98e-fa3c-47e2-8b4f-c7d348c2cba7) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by serena-ruan** [comment]
@niehaus59 This looks great! Could we run it against website/docs folder as well as that's the source when we snapshot the version?

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [website/docs/getting_started/dotnet_example.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fdocs%2Fgetting_started%2Fdotnet_example.md) | 81 | 100 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5078fd70-3779-4890-bf2f-9fb81a44f8cb) | [:white_check_mark:](# "Successfully processed") |
| [website/docs/getting_started/first_example.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fdocs%2Fgetting_started%2Ffirst_example.md) | 94 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19ae0498-2cdb-471f-b825-8c6fe7b74acf) | [:white_check_mark:](# "Successfully processed") |
| [website/docs/getting_started/first_model.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fdocs%2Fgetting_started%2Ffirst_model.md) | 97 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a5e850f-7494-4bfe-8780-b5c0b52827b3) | [:white_check_mark:](# "Successfully processed") |
| [website/docs/getting_started/installation.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fdocs%2Fgetting_started%2Finstallation.md) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e31dfd27-f1c6-42ef-af4a-4615ddf443df) | [:white_check_mark:](# "Successfully processed") |
| [website/docs/mlflow/autologging.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fdocs%2Fmlflow%2Fautologging.md) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/602c554f-bab1-46ef-bf7c-c5f7e494b671) | [:white_check_mark:](# "Successfully processed") |
| [website/docs/mlflow/examples.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fdocs%2Fmlflow%2Fexamples.md) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/164aadad-da00-4a0f-8ae4-e87bc5bd6fc2) | [:white_check_mark:](# "Successfully processed") |
| [website/docs/mlflow/introduction.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fdocs%2Fmlflow%2Fintroduction.md) | 94 | 100 | 73 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14ad5379-c08b-40dd-8fb9-c7d267cb84c1) | [:white_check_mark:](# "Successfully processed") |
| [website/docs/reference/R-setup.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fdocs%2Freference%2FR-setup.md) | 93 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/35b40a70-bdf7-47cc-bb58-89f8d1799693) | [:white_check_mark:](# "Successfully processed") |
| [website/docs/reference/SAR.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fdocs%2Freference%2FSAR.md) | 90 | 100 | 75 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55619dde-6391-4b63-9919-ca149a162ac2) | [:white_check_mark:](# "Successfully processed") |
| [website/docs/reference/contributing_guide.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fdocs%2Freference%2Fcontributing_guide.md) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79a6396a-3ce1-4286-9d98-320064be5f30) | [:white_check_mark:](# "Successfully processed") |
| [website/docs/reference/cyber.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fdocs%2Freference%2Fcyber.md) | 95 | 100 | 88 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d85044be-2114-4ab8-9d8b-3fe0d3c967c1) | [:white_check_mark:](# "Successfully processed") |
| [website/docs/reference/developer-readme.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fdocs%2Freference%2Fdeveloper-readme.md) | 93 | 100 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f086e454-77a6-4aa7-a020-984a6d7f20da) | [:white_check_mark:](# "Successfully processed") |
| [website/docs/reference/docker.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fdocs%2Freference%2Fdocker.md) | 93 | 100 | 88 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a451771-d2ce-4398-a091-3ccc3aecf940) | [:white_check_mark:](# "Successfully processed") |
| [website/docs/reference/dotnet-setup.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fdocs%2Freference%2Fdotnet-setup.md) | 91 | 100 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7bff702-22c3-46c8-844e-dc920d60bde1) | [:white_check_mark:](# "Successfully processed") |
| [website/docs/reference/vagrant.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fdocs%2Freference%2Fvagrant.md) | 92 | 100 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9939b7aa-9c3a-4318-bd6f-ba04a3bf83e2) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.0/reference/vagrant.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fversioned_docs%2Fversion-0.10.0%2Freference%2Fvagrant.md) | 92 | 100 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84e86d61-ed85-45dc-93e6-f0b6116ce319) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.1/reference/vagrant.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fversioned_docs%2Fversion-0.10.1%2Freference%2Fvagrant.md) | 92 | 100 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce1d0351-15a2-410d-90c1-3afce5cdad57) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/getting_started/dotnet_example.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fversioned_docs%2Fversion-0.10.2%2Fgetting_started%2Fdotnet_example.md) | 81 | 100 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6583526-95aa-4c01-b99a-a67394c118a3) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/getting_started/first_example.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fversioned_docs%2Fversion-0.10.2%2Fgetting_started%2Ffirst_example.md) | 94 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5087266e-e0a9-42af-a283-d5959a0278cd) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/getting_started/first_model.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fversioned_docs%2Fversion-0.10.2%2Fgetting_started%2Ffirst_model.md) | 97 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a454770-0a6a-46bd-bbad-6bc7e4d9a5d4) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/getting_started/installation.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fversioned_docs%2Fversion-0.10.2%2Fgetting_started%2Finstallation.md) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/096a4969-6191-49bb-a153-fbdf1225db42) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/mlflow/autologging.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fversioned_docs%2Fversion-0.10.2%2Fmlflow%2Fautologging.md) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7db54be5-782c-4cfa-b684-4e3a14e73f98) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/mlflow/examples.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fversioned_docs%2Fversion-0.10.2%2Fmlflow%2Fexamples.md) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7160ffda-b864-4b9d-8409-f7d8ef1c88a0) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/mlflow/introduction.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fversioned_docs%2Fversion-0.10.2%2Fmlflow%2Fintroduction.md) | 94 | 100 | 73 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/175ec95f-c1bf-4401-bec6-72ba32d2f457) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/reference/R-setup.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fversioned_docs%2Fversion-0.10.2%2Freference%2FR-setup.md) | 93 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b05f26c-cadf-4638-af69-077116a45eab) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/reference/SAR.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fversioned_docs%2Fversion-0.10.2%2Freference%2FSAR.md) | 90 | 100 | 75 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7aa0617b-bbd4-4f9c-9fd7-7966c717a128) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/reference/contributing_guide.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fversioned_docs%2Fversion-0.10.2%2Freference%2Fcontributing_guide.md) | 100 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/71c545e6-a82d-4454-a586-0c5da03555c4) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/reference/cyber.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fversioned_docs%2Fversion-0.10.2%2Freference%2Fcyber.md) | 95 | 100 | 88 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc49689c-582b-465a-8b29-396aa33e30ed) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/reference/developer-readme.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fversioned_docs%2Fversion-0.10.2%2Freference%2Fdeveloper-readme.md) | 93 | 100 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/624572a1-4bce-425d-a79e-4b591da21537) | [:white_check_mark:](# "Successfully processed") |
| [website/versioned_docs/version-0.10.2/reference/docker.md](https://github.com/microsoft/SynapseML/blob/8a2aa281227821e6852a9cd3f11e82d9ab699e4f/website%2Fversioned_docs%2Fversion-0.10.2%2Freference%2Fdocker.md) | 93 | 100 | 88 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6527af27-77f5-45ea-b9f2-0fa1fc90e229) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by mhamilton723** [comment]
Amazing work @niehaus59! I see that there’s still some files with low correctness scores, are y’all still hacking on those or shall we save for later?

**Comment by niehaus59** [comment]
There are a lot of false positives.  You can't obey every directive without destroying the sense of the original.

**Pull request merged**
