### PR TITLE
build: Return values from TaskKeys

### PR DESCRIPTION
**Pull request by nightscape**
## What changes are proposed in this pull request?

To make `TaskKey`s return values (probably mostly `File`s) instead of `Unit`.
Returning values from tasks is the standard approach in SBT (see e.g. examples [here](https://www.scala-sbt.org/1.x/docs/Task-Graph.html)) and makes it much clearer why one task actually depends on the other by making the passed artifacts explicit.

I made an exemplary change in this PR to show the difference.
If there's agreement to proceed here I would refactor more of the build.

## How is this patch tested?

By running `sbt publishDotNetBase` after the change.

## Does this PR change any dependencies?

- [x] No. You can skip this section.

## Does this PR add a new feature? If so, have you added samples on website?

- [x] No. You can skip this section.

### CODE REVIEW

**Review by mhamilton723 — APPROVED** [review]

**Comment by mhamilton723** [comment]
Thank you!

**Comment by mhamilton723** [comment]
CognitiveProjectSetup -> /home/vsts/work/1/s/cognitive/target/scala-2.12/generated/src/dotnet/synapse/ml/bin/Debug/netstandard2.1/SynapseML.Cognitive.dll
  Successfully created package '/home/vsts/work/1/s/cognitive/target/scala-2.12/generated/package/dotnet/SynapseML.Cognitive.0.10.2-rc339784271b.nupkg'.
[System.IO.FileNotFoundException] Unable to find source settings. File not found '/home/vsts/work/1/s/target/scala-2.12/generated'.
Error: result code: 1
[error] java.lang.Exception: Execution resulted in non-zero exit code: 1
[error] 	at BuildUtils$.runCmd(build.scala:56)
[error] 	at BuildUtils$.publishDotnetAssemblyCmd(build.scala:86)
[error] 	at CodegenPlugin$.$anonfun$projectSettings$29(CodegenPlugin.scala:344)
[error] 	at CodegenPlugin$.$anonfun$projectSettings$29$adapted(CodegenPlugin.scala:339)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:829)
[error] (publishDotnet) java.lang.Exception: Execution resulted in non-zero exit code: 1
[error] Total time: 103 s (01:43), completed Dec 21, 2022, 12:43:29 AM
##[error]Script failed with error: Error: The process '/usr/bin/bash' failed with exit code 1

**Comment by nightscape** [comment]
@mhamilton723 thanks for the feedback. Unfortunately I didn't manage to get the dotnet stuff to run locally on my MacBook. I'll try to find out what's going on here 👍

**Comment by nightscape** [comment]
@mhamilton723 I had missed a call to `publishDotnetAssemblyCmd` in `project/CodegenPlugin.scala`.
Should be fixed now.
Is the kind of change in general fine?
If so, I would try to apply this at more places.

**Review by svotaw — APPROVED** [review]

**Pull request merged**
