### PR TITLE
feat: add metric parameter to lightgbm learners

### PR DESCRIPTION
**Pull request by imatiach-msft**
resolves https://github.com/Azure/mmlspark/issues/631 and https://github.com/Azure/mmlspark/issues/628

### CODE REVIEW

**Comment by candalfigomoro** [comment]
@imatiach-msft 
Does it support multiple evaluation metrics (just like LightGBM)?

**Comment by imatiach-msft** [comment]
@candalfigomoro yes it should, with comma separated metrics.  For early stopping we also use all metrics specified (note early stopping is not provided in native api so R/python and our spark implementation all have their own implementation):
https://github.com/Azure/mmlspark/blob/master/src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala#L211

**Comment by nishant-ai** [comment]
@imatiach-msft 
Does it support just ndcg or ndcg@N as well ?

**Comment by imatiach-msft** [comment]
@nishant-ai I think it should support all lightgbm metrics as specified here:
https://github.com/microsoft/LightGBM/blob/master/docs/Parameters.rst#metric
but for NDCG@N I believe we need to expose the parameter eval_at based on a quick look through the lightgbm docs:
https://github.com/microsoft/LightGBM/blob/master/docs/Parameters.rst#eval_at
specifically for early stopping, the scala version of lightgbm does use the correct comparison function here:
https://github.com/Azure/mmlspark/blob/master/src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala#L215

**Comment by nishant-ai** [comment]
Yes, I meant the eval_at parameter only. I had a look at the code and the eval_at parameter used for @N metrics didn't seem to be exposed, just wanted to confirm that.
Can you please make the changes needed so that NDCG@N can be used as well ? Thanks.

**Comment by nishant-ai** [comment]
Thanks @imatiach-msft !

**Pull request merged**
