### PR TITLE
fix: support Math expressions in markdown doc

### PR DESCRIPTION
**Pull request by memoryz**
Also did some reformatting for the data balance component.

### CODE REVIEW

**Comment by memoryz** [comment]
Old:
image

New:
image

**Review by serena-ruan — APPROVED** [review]
Thanks for fixing the format!

**Review by mhamilton723 — APPROVED** [review]
Nice!

**Review by ms-kashyap — APPROVED** [review]
Wow, thanks for making these changes Jason :)

**Comment by memoryz** [comment]
@mhamilton723 can you help merge the change? It's blocked by some RTests failure which seems irrelevant.

**Pull request merged**
