### PR TITLE
fix: Fix ComputeModelStatistics by casting to double

### PR DESCRIPTION
**Pull request by babaniyi**
## Related Issues/PRs

#xxx

## What changes are proposed in this pull request?
I propose converting the label and prediction columns to type double when they are both present in the data.

_Briefly describe the changes included in this Pull Request._

When the `label` or `prediction` are not both of type double, it throws the `error prediction and label columns invalid or missing`.

To users, this error is not informative as one could spend hours trying to figure out the cause of the error despite the 'label' and 'prediction' variables being present in the data frame.

## How is this patch tested?

- [ ] I have written tests (not required for typo or doc fix) and confirmed the proposed feature/bug-fix/change works.

## Does this PR change any dependencies?

- [ ] No. You can skip this section.
- [ ] Yes. Make sure the dependencies are resolved correctly, and list changes here.

## Does this PR add a new feature? If so, have you added samples on website?

- [ ] No. You can skip this section.
- [ ] Yes. Make sure you have added samples following below steps.

1. Find the corresponding markdown file for your new feature in `website/docs/documentation` folder.
   Make sure you choose the correct class `estimators/transformers` and namespace.
2. Follow the pattern in markdown file and add another section for your new API, including pyspark, scala (and .NET potentially) samples.
3. Make sure the `DocTable` points to correct API link.
4. Navigate to website folder, and run `yarn run start` to make sure the website renders correctly.
5. Don't forget to add `<!--pytest-codeblocks:cont-->` before each python code blocks to enable auto-tests for python samples.
6. Make sure the `WebsiteSamplesTests` job pass in the pipeline.

### CODE REVIEW

**Review by imatiach-msft — DISMISSED** [review]

**Comment by mhamilton723** [comment]
Thank you for this! Will queue build and try to merge in

**Comment by mhamilton723** [comment]
@babaniyi This PR causes alot of errors like:
AnalysisException: cannot resolve 'CAST(rawPrediction AS DOUBLE)' due to data type mismatch: cannot cast struct<type:tinyint,size:int,indices:array<int>,values:array<double>> to double;


Did this pass the unit tests on your side?

**Review by babaniyi — COMMENTED** [review]
@mhamilton723

To correct the struct type mismatch from the prediction columns and other cast issues that may arise, the following are implemented:

- Changed the data type of the label column in the getPredictionAndLabels and getScoresAndLabels methods to DoubleType.
- Modified the selectAndCastToDF method to cast the label column to DoubleType.
- Changed the return type of the addSimpleMetric method to DataFrame.
- Updated the logic in the addSimpleMetric method to handle the double data type.
- Changed the return type of the getMulticlassMetrics method to (Double, Double, Double, Double, Double, Double).

@mhamilton723, I could not write the unit tests correctly, could you please propose how it should be done for future PRs?

**Comment by babaniyi** [comment]
> 

@microsoft-github-policy-service agree

**Comment by mhamilton723** [comment]
Perhaps you could start by adding a failing test here:

https://github.com/microsoft/SynapseML/blob/db6386c6d6a133eb55fbec640012ad82bb526c94/core/src/test/scala/com/microsoft/azure/synapse/ml/train/VerifyComputeModelStatistics.scala#L27

And then show with your update fixes that test case while keeping all the other test cases working.

**Pull request closed without merging**
