### PR TITLE
fix: ONNX model shape inference cannot handle batch with shape [-1]

### PR DESCRIPTION
**Pull request by memoryz**
## Related Issues/PRs

#1902 

## What changes are proposed in this pull request?

Add support in ONNX model shape inference when the input batch has shape [-1].

## How is this patch tested?

- [x] I have written tests (not required for typo or doc fix) and confirmed the proposed feature/bug-fix/change works.

## Does this PR change any dependencies?

- [x] No. You can skip this section.
- [ ] Yes. Make sure the dependencies are resolved correctly, and list changes here.

## Does this PR add a new feature? If so, have you added samples on website?

- [x] No. You can skip this section.
- [ ] Yes. Make sure you have added samples following below steps.

1. Find the corresponding markdown file for your new feature in `website/docs/documentation` folder.
   Make sure you choose the correct class `estimators/transformers` and namespace.
2. Follow the pattern in markdown file and add another section for your new API, including pyspark, scala (and .NET potentially) samples.
3. Make sure the `DocTable` points to correct API link.
4. Navigate to website folder, and run `yarn run start` to make sure the website renders correctly.
5. Don't forget to add `<!--pytest-codeblocks:cont-->` before each python code blocks to enable auto-tests for python samples.
6. Make sure the `WebsiteSamplesTests` job pass in the pipeline.

### CODE REVIEW

**Comment by memoryz** [comment]
@svotaw the root cause of issue #1902 is that the shape inference code throws an error when the input batch looks like a one-dimensional array. I'm not sure why the original implementation throws "Image batch is not a sequence" error, but this error causes the code to fail when the input batch is one-dimensional.

**Comment by memoryz** [comment]
@svotaw please take a look at the changes.

**Review by svotaw — APPROVED** [review]

**Comment by memoryz** [comment]
@mhamilton723 please merge. The fix was [verified by customer](https://github.com/microsoft/SynapseML/issues/1902#issuecomment-1498976512).

**Review by mhamilton723 — APPROVED** [review]

**Pull request merged**
