### PR TITLE
docs: add Broken-Links-Crawler action

### PR DESCRIPTION
**Pull request by ScholliYT**
## Related Issues/PRs

#2022 - Where the Borken-links-Crawler Action was first added @mhamilton723
#2025 - Where the action got replaced by a recursive wget @mhamilton723 

## What changes are proposed in this pull request?

_Briefly describe the changes included in this Pull Request._
This PR reintroduces the [Borken-links-Crawler Action](https://github.com/ScholliYT/Broken-Links-Crawler-Action) with the correct yml syntax for the workflow file. Previously, there was a slight syntax error in yml file preventing it from being executed, see [runs/5610893224](https://github.com/microsoft/SynapseML/actions/runs/5610893224/workflow).

## How is this patch tested?

- [x] I have run the action locally.

## Does this PR change any dependencies?

- [x] No. You can skip this section.
- [ ] Yes. Make sure the dependencies are resolved correctly, and list changes here.

## Does this PR add a new feature? If so, have you added samples on website?

- [x] No. You can skip this section.
- [ ] Yes. Make sure you have added samples following below steps.

### CODE REVIEW

**Comment by ScholliYT** [comment]
@mhamilton723 I saw you tried to use the Broken-Links-Crawler-Action but failed due to some syntax error. In this PR, I configured the Action correctly. If you want to use this instead of the recursive wget, you might think about the following two open questions: 
1. Should this action run on run on *.md file changes?
2. Changing the verbosity level to "warning" or "error"

**Comment by ScholliYT** [comment]
@microsoft-github-policy-service agree

**Comment by ScholliYT** [comment]
Running the action right now finds just one broken link on the page: https://microsoft.github.io/SynapseML/docs/Explore%20Algorithms/AI%20Services/Advanced%20Usage%20-%20Async,%20Batching,%20and%20Multi-Key/
referencing a 404 in the Learn More section: https://microsoft.github.io/SynapseML/docs/Explore%20Algorithms/CognitiveServices%20-%20Overview/

<details>
  <summary>Action Logs</summary>

```
WARNING:deadseeker.clientsession:::warn ::Retry Attempt #2 of 5: https://microsoft.github.io/SynapseML/docs/Explore%20Algorithms/CognitiveServices%20-%20Overview/
WARNING:deadseeker.clientsession:::warn ::Retry Attempt #3 of 5: https://microsoft.github.io/SynapseML/docs/Explore%20Algorithms/CognitiveServices%20-%20Overview/
WARNING:deadseeker.clientsession:::warn ::Retry Attempt #4 of 5: https://microsoft.github.io/SynapseML/docs/Explore%20Algorithms/CognitiveServices%20-%20Overview/
WARNING:deadseeker.clientsession:::warn ::Retry Attempt #5 of 5: https://microsoft.github.io/SynapseML/docs/Explore%20Algorithms/CognitiveServices%20-%20Overview/
ERROR:deadseeker.loggingresponsehandler:::error ::ClientResponseError: 404 - https://microsoft.github.io/SynapseML/docs/Explore%20Algorithms/CognitiveServices%20-%20Overview/ found by navigating through: https://microsoft.github.io/SynapseML/ -> https://microsoft.github.io/SynapseML/docs/Explore%20Algorithms/AI%20Services/Overview/#text-analytics-sample -> https://microsoft.github.io/SynapseML/docs/Explore%20Algorithms/AI%20Services/Advanced%20Usage%20-%20Async,%20Batching,%20and%20Multi-Key/
CRITICAL:__main__:::error ::Found some broken links!
```

</details>

**Comment by mhamilton723** [comment]
> @mhamilton723 Alright, that makes sense to me. Especially from a maintainability point of view. Let me know any feedback you have, happy to improve it.

- You might want to display all the dead links in a final printout for ease of finding them all
- Your demo github action should be a fully completed action with the manual_dispatch trigger to help idiots like me copy paste without thinking :)

**Comment by ScholliYT** [comment]
>     * You might want to display all the dead links in a final printout for ease of finding them all
This is a good one. I personally use the verbosity level on "ERROR" to get this kind of summary but a polished summary would be nice 😄 

>     * Your demo github action should be a fully completed action with the manual_dispatch trigger to help idiots like me copy paste without thinking :)
That's a good idea. I fixed the example: https://github.com/ScholliYT/Broken-Links-Crawler-Action#basic-scan-with-retry

**Pull request closed without merging**
