### PR TITLE
test: Update test to validate ATE value should be positive with the test data

### PR DESCRIPTION
**Pull request by dylanw-oss**
## Related Issues/PRs
#1820 

## What changes are proposed in this pull request?
update test to cover the validation of ATE value, ensures we don't have a flipped treatment effect.

### CODE REVIEW

**Comment by dylanw-oss** [comment]
@mhamilton723 , thanks for reviewing and approving #1820, I planned to add this test to it, but you made it so fast this time 👍 So I created a new PR for it.

**Review by mhamilton723 — APPROVED** [review]

**Comment by mhamilton723** [comment]
> @mhamilton723 , thanks for reviewing and approving #1820, I planned to add this test to it, but you made it so fast this time 👍 So I created a new PR for it.

Sorry i get excited when i see green builds lol

**Pull request merged**
