### PR TITLE
chore: add support for dimensions parameter to OpenAIEmbedding

### LINKED ISSUE #2177: How to use text-embedding-3-small with different output dimensions?
Could you please provide me with information on how to use text-embedding-3-small model with various output dimensions? Also, is there any estimated timeline for this?
```[tasklist]
### Tasks
```

### PR DESCRIPTION
**Pull request by gramhagen**
## Related Issues/PRs

Closes #2177 

## What changes are proposed in this pull request?

Adding support for `dimensions` parameter when calling OpenAI Embeddings endpoint to reduce the size of the embedding vecor.

## How is this patch tested?

Added `Extra Param Usage` test to OpenAIEmbeddingSuite

- [X] I have written tests (not required for typo or doc fix) and confirmed the proposed feature/bug-fix/change works.

## Does this PR change any dependencies?

- [X] No. You can skip this section.
- [ ] Yes. Make sure the dependencies are resolved correctly, and list changes here.

## Does this PR add a new feature? If so, have you added samples on website?

- [ ] No. You can skip this section.
- [X] Yes. Make sure you have added samples following below steps.

Added example to existing OpenAI.md

1. Find the corresponding markdown file for your new feature in `website/docs/documentation` folder.
   Make sure you choose the correct class `estimators/transformers` and namespace.
2. Follow the pattern in markdown file and add another section for your new API, including pyspark, scala (and .NET potentially) samples.
3. Make sure the `DocTable` points to correct API link.
4. Navigate to website folder, and run `yarn run start` to make sure the website renders correctly.
5. Don't forget to add `<!--pytest-codeblocks:cont-->` before each python code blocks to enable auto-tests for python samples.
6. Make sure the `WebsiteSamplesTests` job pass in the pipeline.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum total score of 80 is required.**
 
Select the total score link to review all feedback on clarity, consistency, tone, brand, terms, spelling, grammar, readability, and inclusive language. _You should fix all spelling errors regardless of your total score_. Fixing spelling errors helps maintain customer trust in overall content quality.

| Article | Total score<br>(Required: 80) | Words + phrases<br>(Brand, terms) | Correctness<br>(Spelling, grammar) | Clarity<br>(Readability) |
|---------|:--------------:|:--------------------:|:------:|:---------:|
| [:white_check_mark:](# "Successfully processed") [website/versioned_docs/version-1.0.4/Explore Algorithms/OpenAI/OpenAI.md](https://github.com/microsoft/SynapseML/blob/ee595179c1be7abe5ce9a6eb1f3d43d853e13bb5/website%2Fversioned_docs%2Fversion-1.0.4%2FExplore%20Algorithms%2FOpenAI%2FOpenAI.md) | [77](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/555d89cd-d513-41f6-9fdb-490bc9bc5f21) | 93 | 93 | 51 |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Review by mhamilton723 — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum total score of 80 is required.**
 
Select the total score link to review all feedback on clarity, consistency, tone, brand, terms, spelling, grammar, readability, and inclusive language. _You should fix all spelling errors regardless of your total score_. Fixing spelling errors helps maintain customer trust in overall content quality.

| Article | Total score<br>(Required: 80) | Words + phrases<br>(Brand, terms) | Correctness<br>(Spelling, grammar) | Clarity<br>(Readability) |
|---------|:--------------:|:--------------------:|:------:|:---------:|
| [:white_check_mark:](# "Successfully processed") [website/versioned_docs/version-1.0.4/Explore Algorithms/OpenAI/OpenAI.md](https://github.com/microsoft/SynapseML/blob/6cdf750e17c80a4e08fbbca703efc1fe35832120/website%2Fversioned_docs%2Fversion-1.0.4%2FExplore%20Algorithms%2FOpenAI%2FOpenAI.md) | [77](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49162462-8948-486e-80d8-aa2be18efb76) | 93 | 93 | 51 |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum total score of 80 is required.**
 
Select the total score link to review all feedback on clarity, consistency, tone, brand, terms, spelling, grammar, readability, and inclusive language. _You should fix all spelling errors regardless of your total score_. Fixing spelling errors helps maintain customer trust in overall content quality.

| Article | Total score<br>(Required: 80) | Words + phrases<br>(Brand, terms) | Correctness<br>(Spelling, grammar) | Clarity<br>(Readability) |
|---------|:--------------:|:--------------------:|:------:|:---------:|
| [:white_check_mark:](# "Successfully processed") [website/versioned_docs/version-1.0.4/Explore Algorithms/OpenAI/OpenAI.md](https://github.com/microsoft/SynapseML/blob/d59f4171dad7698634b6b6192526a60ca0500922/website%2Fversioned_docs%2Fversion-1.0.4%2FExplore%20Algorithms%2FOpenAI%2FOpenAI.md) | [77](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bab6430e-660a-422f-aaa7-f1b439eb2cc7) | 93 | 93 | 51 |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum total score of 80 is required.**
 
Select the total score link to review all feedback on clarity, consistency, tone, brand, terms, spelling, grammar, readability, and inclusive language. _You should fix all spelling errors regardless of your total score_. Fixing spelling errors helps maintain customer trust in overall content quality.

| Article | Total score<br>(Required: 80) | Words + phrases<br>(Brand, terms) | Correctness<br>(Spelling, grammar) | Clarity<br>(Readability) |
|---------|:--------------:|:--------------------:|:------:|:---------:|
| [:white_check_mark:](# "Successfully processed") [website/versioned_docs/version-1.0.4/Explore Algorithms/OpenAI/OpenAI.md](https://github.com/microsoft/SynapseML/blob/286cdaae3c1870f20c211fae9d5ffa9ad09a7b08/website%2Fversioned_docs%2Fversion-1.0.4%2FExplore%20Algorithms%2FOpenAI%2FOpenAI.md) | [77](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54348a9b-bb7d-47f3-b070-cbc42d72bff1) | 93 | 93 | 51 |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Pull request merged**
