### PR TITLE
docs: Adding a multivariate anomaly detection sample notebook 

### PR DESCRIPTION
**Pull request by yalaudah**
SynapseML v0.9.5 added support for multivariate anomaly detection. Here's a sample notebook that hopefully helps demonstrate this capability. 

You can view the rendered version of the notebook [here](https://github.com/yalaudah/SynapseML/blob/master/notebooks/features/cognitive_services/CognitiveServices%20-%20Multivariate%20Anomaly%20Detection.ipynb).

~~**Note**: Please let me know where I can upload the `sample.csv` file I'm using in the notebook. I've seen other notebooks in the repo use `wasbs://publicwasb@mmlspark.blob.core.windows.net/iot` but I don't have access to upload any file there.~~

### CODE REVIEW

**Comment by yalaudah** [comment]
I just updated the URL of the sample CSV to point to `wasbs://publicwasb@mmlspark.blob.core.windows.net/MVAD/sample.csv`.

Thanks @serena-ruan !

**Comment by serena-ruan** [comment]
Hey @yalaudah, could you update that first cell of getting anomaly_key to something like this notebook (https://github.com/microsoft/SynapseML/blob/master/notebooks/features/cognitive_services/CognitiveServices%20-%20Overview.ipynb) 
image
Just anomaly_key though. Thanks!

**Comment by serena-ruan** [comment]
Also, after you address the above comment, please delete this spark creation part:
image
spark = pyspark.sql.SparkSession.builder.appName("MyApp") \
            .config("spark.jars.packages", "com.microsoft.azure:synapseml_2.12:0.9.5") \
            .config("spark.jars.repositories", "https://mmlspark.azureedge.net/maven") \
            .getOrCreate()
We don't need this anymore, and we will install the corresponding version automatically during tests; for customers, they should follow the guidance in website installation section to install the package.
(Sorry I'm leaving comments like this because the notebook doesn't render correctly on my side)

**Comment by yalaudah** [comment]
Thanks @serena-ruan! I've updated the notebook to address the two comments above.

**Comment by mhamilton723** [comment]
Hey @yalaudah  thank you so much for this PR. I gave you access to queue builds with /azp run.

**Comment by serena-ruan** [comment]
Hi @yalaudah For the website to successfully render the notebook, I suggest you sending over the image to me and I could upload it to the storage account for you, then we just render it with a link. BTW, I should have fixed that databricks key error, and this image stuff should be our last step to get this PR in :)

**Comment by mhamilton723** [comment]
@yalaudah this looks like an error due to secrets not being in databricks env. i added and requeued

**Pull request merged**
