### PR TITLE
docs: Adding document and notebook for Data Balance Analysis

### PR DESCRIPTION
**Pull request by ms-kashyap**

### CODE REVIEW

**Comment by memoryz** [comment]
> @memoryz @mhamilton723 Where do you guys think I should host the Data Balance Analysis md? Currently, I have it in "features" under a new folder named "exploratory". However, do you guys have suggestions for better places than this?

I think having the folder structure matching the package name is a good idea. In the future, we might want to bundle this with the explainers into a rai module, so the doc can be moved together.

**Review by memoryz — APPROVED** [review]

**Review by mhamilton723 — APPROVED** [review]

**Pull request merged**
