### PR TITLE
fix: Add spark config to fix ArrayStoreException in Synapse - Add back HyperparameterTuning nbs to test pipeline

### PR DESCRIPTION
**Pull request by k-rush**
## What changes are proposed in this pull request?

This turns off a spark setting which leads to ArraystoreExceptions while using HyperparameterTuning notebooks.

## How is this patch tested?

Re-adding tests to the E2E tests which run in pr pipeline

## Does this PR change any dependencies?

- [x] No. You can skip this section.
- [ ] Yes. Make sure the dependencies are resolved correctly, and list changes here.

## Does this PR add a new feature? If so, have you added samples on website?

- [x] No. You can skip this section.
- [ ] Yes. Make sure you have added samples following below steps.

1. Find the corresponding markdown file for your new feature in `website/docs/documentation` folder.
   Make sure you choose the correct class `estimators/transformers` and namespace.
2. Follow the pattern in markdown file and add another section for your new API, including pyspark, scala (and .NET potentially) samples.
3. Make sure the `DocTable` points to correct API link.
4. Navigate to website folder, and run `yarn run start` to make sure the website renders correctly.
5. Don't forget to add `<!--pytest-codeblocks:cont-->` before each python code blocks to enable auto-tests for python samples.
6. Make sure the `WebsiteSamplesTests` job pass in the pipeline.

### CODE REVIEW

**Review by mhamilton723 — DISMISSED** [review]

**Comment by JessicaXYWang** [comment]
testing config changes https://github.com/microsoft/SynapseML/pull/1807 for Hyperparameter tunning nb test exclusion

**Comment by JessicaXYWang** [comment]
all test passed except synapse-internal. Will remove hyperparameter exclusion after https://github.com/microsoft/SynapseML/pull/1807 merged in. thanks @k-rush and @memoryz !

**Pull request merged**
