### PR TITLE
docs: add aisample title genre text classification

### PR DESCRIPTION
**Pull request by thinkall**
## Related Issues/PRs

None

## What changes are proposed in this pull request?

Add a title genre text classification notebook for aisample under notebooks/community/aisample.

## How is this patch tested?

- [ ] I have written tests (not required for typo or doc fix) and confirmed the proposed feature/bug-fix/change works.

## Does this PR change any dependencies?

- [x] No. You can skip this section.
- [ ] Yes. Make sure the dependencies are resolved correctly, and list changes here.

## Does this PR add a new feature? If so, have you added samples on website?

- [x] No. You can skip this section.
- [ ] Yes. Make sure you have added samples following below steps.

1. Find the corresponding markdown file for your new feature in `website/docs/documentation` folder.
   Make sure you choose the correct class `estimators/transformers` and namespace.
2. Follow the pattern in markdown file and add another section for your new API, including pyspark, scala (and .NET potentially) samples.
3. Make sure the `DocTable` points to correct API link.
4. Navigate to website folder, and run `yarn run start` to make sure the website renders correctly.
5. Don't forget to add `<!--pytest-codeblocks:cont-->` before each python code blocks to enable auto-tests for python samples.
6. Make sure the `WebsiteSamplesTests` job pass in the pipeline.

AB#1935137

### CODE REVIEW

**Review by mhamilton723 — CHANGES_REQUESTED** [review]
Lovely work heres a few suggestions!

- No need for this line: raw_df.createOrReplaceTempView("raw_data")
-   are these lines necessary for this CSV?
 ```
 multiLine=True,
    quote='"',
    escape='"',
```

- We have a class balancer tool specifically to deal with label imbalence, this will add a weight thats proportional to the deficit https://microsoft.github.io/SynapseML/docs/next/documentation/estimators/estimators_core/#classbalancer

- We have text featurizer that might be able to make alot of these steps a single model call
https://mmlspark.blob.core.windows.net/docs/0.10.0/pyspark/synapse.ml.featurize.text.html#module-synapse.ml.featurize.text.TextFeaturizer

- `EvaluatorType` -> use snake_case here and elsewhere

**Comment by thinkall** [comment]
Thanks @mhamilton723 for the feedbacks. They helped a lot :-)

Just TextFeaturizer is not applied. The output column only contains indexes of words, not the words. Thus we can't use the output df for plotting word cloud. Moreover, we want to apply word2vec for vectorization. It seems that TextFeaturizer doesn't support it.

**Review by mhamilton723 — APPROVED** [review]

**Review by mhamilton723 — APPROVED** [review]

**Pull request merged**
